### PR TITLE
[API/Librus] Fix TeacherFreeDays API problems

### LINKED ISSUE #214: Librus API teacher
Bug from 2021 is back

Image

### PR DESCRIPTION
**Pull request by KrystianQur**
Resolves #214

### CODE REVIEW

File: app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/librus/Librus.kt [hunk 1]
```diff
@@ -235,6 +235,9 @@ class Librus(val app: App, val profile: Profile?, val loginStore: LoginStore, va
                                 data.app.config.sync.tokenLibrusList + data.profileId
                         data()
                     }
+                    ERROR_LIBRUS_API_TEACHER_FREE_DAYS_NOT_PUBLIC -> {
+                        d(TAG, "Student not have access to Teacher Free Days resource")
```
Comment (kuba2k2) [inline app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/librus/Librus.kt:239]: This will lock up the sync, you probably forgot to add the `data()` call here - see other errors above as examples.

It would also be good to call `data.setSyncNext(...)` here, but with a longer interval, like 7 days, since it's unlikely that the resource access will be restored anyway. See `LibrusApiTeacherFreeDays.kt` for an example.

**Review by kuba2k2 — CHANGES_REQUESTED** [review]

File: app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/librus/Librus.kt (hunk 1 above)
Comment (KrystianQur) [reply app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/librus/Librus.kt:239]: Changed

File: app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/librus/Librus.kt [hunk 2]
```diff
@@ -235,9 +238,14 @@ class Librus(val app: App, val profile: Profile?, val loginStore: LoginStore, va
...
+                        data.setSyncNext(ENDPOINT_LIBRUS_API_TEACHER_FREE_DAYS, 1 * WEEK, FeatureType.AGENDA)
+                        data()
+                    }
                     else -> callback.onError(apiError)
                 }
             }
         }
     }
-}
+}
```
Comment (kuba2k2) [inline app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/librus/Librus.kt:251]:
```suggestion
}

```

**Review by kuba2k2 — CHANGES_REQUESTED** [review]

**Review by kuba2k2 — APPROVED** [review]
